### ISSUE TITLE
Extension isn't working at all

### ISSUE THREAD

**Issue by Versiris** [ahallaha/tcgplayer-seller-flagger#8]
Would really love to figure out why. Chrome Version 113.0.5672.92.

**Comment by ahallaha** [comment]
It's working for me with Chrome version 113.0.5672.63 on Windows but I was seeing some weird behavior where it wasn't doing anything at first until I refreshed then it started working as expected. I will update my browser and do some more testing this weekend and see if I can reproduce and solve the issue you're having.

**Comment by ahallaha** [comment]
I updated Chrome and did a fresh install of the extension and I didn't have any issues. Do you have any ad or script blocker extensions installed?

https://github.com/ahallaha/tcgplayer-seller-flagger/assets/104538552/66da3480-4c88-4688-b08d-3098ef768c6c

**Comment by ahallaha** [comment]
Ok, I actually forgot to check the cart. I do see that it's not working over there anymore. It looks like they updated the design of the shopping cart page so I'll see what needs to be done to fix it. I'm guessing some class names changed with the new design and I just need to update the selectors I'm using.

**Comment by ahallaha** [comment]
Just wanted to drop in and say this is mostly fixed minus a couple of things.
- I need to update the CSS for the highlighted cells in the cart
- I've noticed some instances where I have to refresh to load the changes at times when I shouldn't have to.

I should be able to get these resolved soon and the update pushed.
![image](https://github.com/ahallaha/tcgplayer-seller-flagger/assets/104538552/725631b2-3939-493a-b7d9-49f717789a6c)

**Comment by ahallaha** [comment]
Just want to give you a heads-up that this fix has finally been published. In addition to the cart redesign, tcgplayer also implemented client-side routing which fundamentally broke how the extension worked. Sorry that this fix took a lot longer than expected.
